apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deploymentt
  labels:
    app: ekartt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ekartt
  template:
    metadata:
      labels:
        app: ekartt
    spec:
      containers:
        - name: ekart-container
          image: devopsproject1.azurecr.io/ekartshopping:latest
          ports:
            - containerPort: 8070
